// @generated - do not edit by hand; regenerate with `bun run openapi:generate`.
// Source: apps/api/openapi.yaml
// source-sha256: a62744248980f3986411302bdb509268f05c72d4d80702e5a9a55537cb8b9598
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liveness probe */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The API is up. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["HealthResponse"];
					};
				};
				429: components["responses"]["RateLimited"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Exchange email and password for an access token
		 * @description On success the refresh token is set in an httpOnly cookie and only the
		 *     access token (plus its lifetime) is returned in the body.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["LoginRequest"];
				};
			};
			responses: {
				/** @description Credentials accepted. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["TokenResponse"];
					};
				};
				400: components["responses"]["BadRequest"];
				/**
				 * @description Invalid credentials. A wrong password and a non-existent account
				 *     are indistinguishable on purpose.
				 */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				/**
				 * @description The credentials are correct but the email is not verified. The
				 *     machine-readable `code` is `email_not_verified`.
				 */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CodedError"];
					};
				};
				429: components["responses"]["RateLimitedStrict"];
				500: components["responses"]["InternalServerError"];
				503: components["responses"]["IdentityProviderUnavailable"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register a new account
		 * @description The response is identical whether the account was created or the
		 *     sign-up was rejected (for example a duplicate email): the API must not
		 *     reveal which one it was.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RegisterRequest"];
				};
			};
			responses: {
				/**
				 * @description Account created, or the sign-up was rejected without revealing
				 *     which.
				 */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["RegisterResponse"];
					};
				};
				400: components["responses"]["BadRequest"];
				429: components["responses"]["RateLimitedStrict"];
				500: components["responses"]["InternalServerError"];
				503: components["responses"]["IdentityProviderUnavailable"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Exchange the refresh cookie for a fresh token pair
		 * @description The refresh token is read from the httpOnly cookie, never from the
		 *     body. On success the cookie is rotated when the provider issues a new
		 *     refresh token.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Refresh token accepted. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["TokenResponse"];
					};
				};
				/**
				 * @description The refresh cookie is missing or the provider rejected it. The
				 *     message is uniform so a missing cookie and an expired token are
				 *     indistinguishable.
				 */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				429: components["responses"]["RateLimitedStrict"];
				500: components["responses"]["InternalServerError"];
				503: components["responses"]["IdentityProviderUnavailable"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Clear the refresh-token cookie
		 * @description Deliberately not behind authentication: an expired access token must
		 *     not block signing out. No provider revocation is performed.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The refresh cookie is cleared; no body is returned. */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				429: components["responses"]["RateLimited"];
				500: components["responses"]["InternalServerError"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/companies": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List the caller's companies */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The companies the caller belongs to. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Company"][];
					};
				};
				401: components["responses"]["Unauthorized"];
				/**
				 * @description The token resolves to no user; the `code` is
				 *     `user_not_provisioned`.
				 */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CodedError"];
					};
				};
				429: components["responses"]["RateLimited"];
				500: components["responses"]["InternalServerError"];
			};
		};
		put?: never;
		/** Create a company */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreateCompanyRequest"];
				};
			};
			responses: {
				/** @description Company created. */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Company"];
					};
				};
				400: components["responses"]["BadRequest"];
				401: components["responses"]["Unauthorized"];
				/**
				 * @description The token resolves to no user; the `code` is
				 *     `user_not_provisioned`.
				 */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CodedError"];
					};
				};
				429: components["responses"]["RateLimited"];
				500: components["responses"]["InternalServerError"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/companies/{companyId}/context": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Resolve the caller's membership context in a company */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					companyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description The company and the caller's role in it. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CompanyContextResponse"];
					};
				};
				/** @description The company id is not a UUID. */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				401: components["responses"]["Unauthorized"];
				/**
				 * @description Either the token resolves to no user (`user_not_provisioned`) or
				 *     the caller has no ACTIVE membership in the company
				 *     (`company_access_forbidden`). A non-existent company and a
				 *     non-member are answered identically so company ids cannot be
				 *     enumerated.
				 */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CodedError"];
					};
				};
				429: components["responses"]["RateLimited"];
				500: components["responses"]["InternalServerError"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/companies/{companyId}/media/signature": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign upload parameters for a direct-to-storage upload
		 * @description The request body is ignored: every upload parameter is decided by the
		 *     server from the company id, so the signed contract is always the
		 *     server's, never the caller's.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					companyId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Signed upload parameters for the storage provider. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["MediaUploadSignature"];
					};
				};
				/** @description The company id is not a UUID. */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Error"];
					};
				};
				401: components["responses"]["Unauthorized"];
				/**
				 * @description Either the token resolves to no user (`user_not_provisioned`) or
				 *     the caller has no ACTIVE membership in the company
				 *     (`company_access_forbidden`). A non-existent company and a
				 *     non-member are answered identically so company ids cannot be
				 *     enumerated.
				 */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CodedError"];
					};
				};
				429: components["responses"]["RateLimited"];
				500: components["responses"]["InternalServerError"];
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		HealthResponse: {
			/** @example ok */
			status: string;
			uptime: number;
		};
		LoginRequest: {
			/** Format: email */
			email: string;
			password: string;
		};
		RegisterRequest: {
			/** Format: email */
			email: string;
			password: string;
		};
		TokenResponse: {
			accessToken: string;
			/** @description Access-token lifetime in seconds. */
			expiresIn: number;
		};
		RegisterResponse: {
			message: string;
		};
		Company: {
			/** Format: uuid */
			id: string;
			name: string;
			/** Format: date-time */
			createdAt: string;
		};
		CreateCompanyRequest: {
			name: string;
		};
		CompanyContextResponse: {
			company: components["schemas"]["Company"];
			/** @enum {string} */
			role: "OWNER" | "ADMIN" | "MEMBER";
		};
		MediaUploadSignature: {
			cloudName: string;
			apiKey: string;
			timestamp: number;
			signature: string;
			folder: string;
			allowedFormats: string[];
			maxFileSizeBytes: number;
		};
		Error: {
			error: {
				message: string;
			};
		};
		ValidationError: {
			error: {
				message: string;
				issues: string[];
			};
		};
		/**
		 * @description The JSON body could not be parsed. The body parser rejects it before it
		 *     reaches validation, so the response carries only `message` and never
		 *     `issues`. `additionalProperties: false` keeps this shape disjoint from
		 *     `ValidationError`, so the `BadRequest` `oneOf` stays unambiguous.
		 */
		MalformedJsonError: {
			error: {
				message: string;
			};
		};
		CodedError: {
			error: {
				message: string;
				code: string;
			};
		};
	};
	responses: {
		/**
		 * @description The request body is malformed or fails validation. The response shape
		 *     depends on which failure happened:
		 *     - a syntactically invalid JSON body is rejected by the body parser
		 *       before it reaches validation and is answered as `{error: {message}}`
		 *       with no `issues`;
		 *     - a body that parses but fails the request schema is answered as
		 *       `{error: {message, issues}}`.
		 */
		BadRequest: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json":
					| components["schemas"]["ValidationError"]
					| components["schemas"]["MalformedJsonError"];
			};
		};
		/** @description The bearer token is missing, invalid or expired. */
		Unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description The identity provider could not be reached. */
		IdentityProviderUnavailable: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/**
		 * @description An unexpected server error. The message is fixed and generic so
		 *     internal details never leak to the client.
		 */
		InternalServerError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/**
		 * @description Too many requests from this client. The global limiter applies to every
		 *     route. `express-rate-limit` answers with a plain string, which Express
		 *     sends as `text/html`.
		 */
		RateLimited: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"text/html": string;
			};
		};
		/**
		 * @description Too many requests from this client. This endpoint has a stricter
		 *     dedicated limiter in addition to the global one. `express-rate-limit`
		 *     answers with a plain string, which Express sends as `text/html`.
		 */
		RateLimitedStrict: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"text/html": string;
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
