import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Drift guard for the committed generated types.
 *
 * The generator stamps `apps/web/lib/api/openapi.d.ts` with the SHA-256 of
 * `apps/api/openapi.yaml` at generation time. This test recomputes that hash
 * and compares it to the stamp, so a spec change that was not followed by a
 * regeneration fails here - offline, cheap, and without running the generator
 * (which needs the network or a warm `bunx` cache).
 *
 * Strength, stated honestly: this proves the committed file is stale relative
 * to the spec, not that the generated *content* is semantically correct. If
 * the generator itself mis-renders a schema, the stamp would still match and
 * this test would not notice. That residual risk is accepted: the artifact is
 * deterministic and generated by `openapi-typescript`, and the stamp makes the
 * common failure (forgot to regenerate after an edit) visible in CI.
 */
const SPEC_PATH = join(__dirname, "../../../api/openapi.yaml");
const GENERATED_PATH = join(__dirname, "./openapi.d.ts");

function sha256(contents: Buffer): string {
	return createHash("sha256").update(contents).digest("hex");
}

describe("openapi.d.ts drift guard", () => {
	it("is stamped with the SHA-256 of the spec it was generated from", () => {
		const spec = readFileSync(SPEC_PATH);
		const generated = readFileSync(GENERATED_PATH, "utf8");

		const expected = sha256(spec);
		const stamp = generated.match(/source-sha256:\s*([0-9a-f]{64})/)?.[1];

		expect(stamp).toBeDefined();
		expect(stamp).toBe(expected);
	});
});
